[project]
name = "blender-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "bpy>=4.2.0",
    "pydantic>=2.9.2",
]
